### ISSUE TITLE
[Improvement] Please add support of the UNC path

### ISSUE THREAD

**Issue by valentinfltv** [yaser01/mkv-muxing-batch-gui#78] opened 2023-01-29 08:43 UTC
Hi, thanks for your efforts - this utility is brilliant, simple and powerful.
Yet I faced with issue - when adding UNC path e.g "\\ComputerName\SharedFolder" I've got an error that path is invalid. Not sure why this check in path validation was implemented, yet it will be nice to have possibility of working with shared storages.

**Comment by animefn** [comment] 2023-01-29 22:05
Even if this GUI supported UNC, are you sure the underlying mkvtoolnix backend tools will support your UNC path? Can you use that same path with mkvtoolnix directly?

See : https://gitlab.com/mbunkus/mkvtoolnix/-/issues/3058

Next version of mkvtoolnix will be using boost to fix support for UNC in mkvtoolnix.

**Comment by valentinfltv** [comment] 2023-02-26 08:48
According to the mkvtoolnix release notes the UNC issue is already fixed.
Version 74.0.0
Bug fixes:
all: Windows: UNC paths of type \\?\C:\… are supported again by switching back to Boost's file system library instead of using C++17's file system library. Fixes [#3058](https://gitlab.com/mbunkus/mkvtoolnix/issues/3058).
JFYI

**Comment by animefn** [comment] 2023-03-05 23:02
@valentinfltv 
That version was not released when I posted.

I am the one who requested that fix from Moritz before you even post this issue.

JFYI.

Implementing that feature back then in mmbg was meaningless, that is what I tried to say. Now it makes perfect sense.

**Comment by yaser01** [comment] 2023-05-09 06:58
@valentinfltv 
doesn't UNC should start with "\\" instead of "\"  [UNC Paths](https://learn.microsoft.com/en-us/dotnet/standard/io/file-path-formats#unc-paths)
Can you be more specific where this happen in input paths [video ,subtitle,...] or output path[video destination path]?

**Comment by yaser01** [comment] 2023-05-12 06:00
@eddilara Oh I see...

**Comment by valentinfltv** [comment] 2023-05-17 19:12
@yaser01 sorry for the delayed answer, here are some details:
The single '\' at the beginning of the given link example is just a mistype.

So, when set the UNC path as Destination path, MKV Muxing Batch shows "isn't a valid path" error, see the screenshot:
<img width="1792" alt="Screenshot 2023-05-17 at 21 47 22" src="https://github.com/yaser01/mkv-muxing-batch-gui/assets/12237998/42323d88-c90b-4fb8-9a81-4dfbb0b2e875">

At the same time, latest available MKV merge exports files to the same path without issues: 
<img width="1792" alt="Screenshot 2023-05-17 at 21 53 44" src="https://github.com/yaser01/mkv-muxing-batch-gui/assets/12237998/ed76a4fe-5102-4c7a-80b8-cd46e8e0ebe1">

I'm not a big expert, but if update mkv merge (is it moritz edition?) in the MKV Muxing Batch tool and remove check from the gui part (probably the one that located in /packages/Tabs/MuxSetting /MuxSetting.py) - it will accept UNC paths.

**Comment by yaser01** [comment] 2023-05-20 14:24
@valentinfltv, I see this I won't say a duplicate of #90 but kind of 
I will Fix it soon :D

**Comment by yaser01** [comment] 2024-01-06 11:57
Try 2.4 Update :D

**Closed by yaser01** 2024-01-06 11:57 UTC
Labels: bug, Implemented
